# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - vote/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'c8325d8f-5e98-46a3-941e-ee7ec0a72f36'
  imageRepository: 'votingapplication'
  containerRegistry: 'votingappacr002.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/vote/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
pool:
  name: azureagent  # Self-hosted agent

stages:
- stage: ImageBuild
  displayName: Build Vote Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build 
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'vote/Dockerfile'
        tags: '$(tag)'
- stage: ImagePush
  displayName: Push Vote Image
  jobs:
    - job: Push
      displayName: Push Image
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: '$(dockerRegistryServiceConnection)'
            repository: '$(imageRepository)'
            command: 'push'
            Dockerfile: 'vote/Dockerfile'
            tags: '$(tag)'

- stage: Update
  displayName: Update vote app Deployment Manifests
  jobs:
    - job: Update
      displayName: Update vote app Deployment Manifests
      steps:
        - task: ShellScript@2
            #docker pull votingappacr001.azurecr.io/votingapplication:80
