# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - result/*

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6ce42fb4-bf98-4730-b985-5cc8fbe3b235'
  imageRepository: 'resultapp'                # only for result app
  containerRegistry: 'votingappacr001.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'   # Docker file path for result app
  tag: '$(Build.BuildId)'

  # Agent VM image name
pool:
  name: azureagent

stages:
- stage: ImageBuild
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        Dockerfile: 'result/Dockerfile'
        tags: '$(tag)'
- stage: ImagePush
  displayName: Push Docker Image
  jobs:
    - job: Push
      displayName: Push Image
      steps:
      - task: Docker@2
        displayName: Push Image
        inputs:
          containerRegistry: '$(dockerRegistryServiceConnection)'
          repository: '$(imageRepository)'
          command: 'push'
          Dockerfile: 'result/Dockerfile'
          tags: '$(tag)'